### PR TITLE
force displaymath for inline limits

### PR DESCRIPTION
**Pull request by StevenClontz**
Addresses #138

### CODE REVIEW

**Review by siwelwerd — APPROVED** [review]

**Comment by AbbyANoble** [comment]
Questions -- does merged and committed mean it's fixed on the live version? Because I'm not seeing it if so.

**Comment by siwelwerd** [comment]
It means the source code has been fixed.  There is a separate "deploy" step that builds and publishes the HTML on the website.  Looking at the [front matter](https://teambasedinquirylearning.github.io/calculus/2024e/frontmatter.html), it was deployed in December, before this fix, so that's why you are not seeing it.

Generally we avoid any deploys mid-semester because we don't want to change numbering or something on someone mid-semester while they are teaching with it.

**Comment by AbbyANoble** [comment]
Gotcha. So many words that mean "fix"! haha.

**Comment by StevenClontz** [comment]
I need to fix this repo so we can deploy a "2024 Edition PREVIEW". Will do this now...

**Pull request merged**
