### PR TITLE
AI3 sageplots

### LINKED ISSUE #111: Sage pictures not displaying?
@StevenClontz I assume that in the Calculus book we want sage pictures to just display, not have a sage code cell appear and then have to **evaluate** the code to display the picture. If this is a choice that was made, it might impact several users so I think for the not development version to just have generated images.

Example: https://teambasedinquirylearning.github.io/calculus/2023/AI3.html

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #111

### CODE REVIEW

**Comment by StevenClontz** [comment]
Opened support thread at https://groups.google.com/g/pretext-support/c/FF8Xv-5GSIA to see why the first (of a few) images won't build as sageplots.

**Review by siwelwerd — COMMENTED** [review]
Is there a good reason the sage files have terrible names?  Or can we give them more descriptive names?

Also, what's the motivation for factoring them out into separate files when they are 8 or 9 lines?  Why are we doing that only in this section, and not in the rest of the book?

**Comment by StevenClontz** [comment]
> Is there a good reason the sage files have terrible names? Or can we give them more descriptive names?

I was feeling very uncreative and just decided to get things working with unique IDs. But, yes, that should be cleaned up before merging.

> Also, what's the motivation for factoring them out into separate files when they are 8 or 9 lines? Why are we doing that only in this section, and not in the rest of the book?

Well, I would do this in the rest of the book. By writing them in actual sage files, they can be called by sage, get syntax highlighting, etc. etc. And we don't have to do any escaping of `<`, `>`, and `&`.

**Review by siwelwerd — APPROVED** [review]
Okay, I made a separate issue to factor out sageplot code into separate files in the rest of the book (that can be a longer term thing). I am going ahead and marking this as approved, to be merged as soon as the filenames are fixed.

**Pull request merged**
