### PR TITLE
AI4 ask about both axes

### LINKED ISSUE #87: CheckIt AI4 missing axis of revolution
The [CheckIt Problems for AI4](https://teambasedinquirylearning.github.io/calculus/2022/exercises/#/bank/AI4/1/) involve rotating a curve around an axis and determining, or estimating, the surface area generated. The problem prompt doesn't supply the axis. This is important to list as [Activity 6.4.3](https://teambasedinquirylearning.github.io/calculus/2023/AI4.html#activity-385) 
asks students to write integrals for both x-axis and y-axis rotation, so leaving off the axis leads to student confusion.

### PR DESCRIPTION
**Pull request by siwelwerd**
Closes #87

This makes a couple of changes to AI4.  First, there are two tasks, asking them to write the integral for rotating about each of the x and y axes.  I initially thought about randomly choosing one of the two, but this means half the time students have to invert the given function, and half the time they don't leading to a difficulty mismatch.  By asking for both, on one of them they do and on one of them they don't.

Second, I implemented a randomization between giving the students a function $y=f(x)$ and a function $x=g(y)$.  This is to make sure they are thinking about which one requires them to invert the function and which one does not.

Some side effects: The bounds can be a little ugly, particularly for the exponential/logarithm.  However, no computation needs to be done with them.

### CODE REVIEW

**Comment by StevenClontz** [comment]
I think @TienChih would be a good person to review this - I seem to recall him thinking along similar lines for his Oxford calculus bank (at least for volumes of revolution). I'll pick this up myself if he doesn't get to it by Tuesday.

**Comment by TienChih** [comment]
My understanding was we were swapping AI4 for these guys: https://tienchih.github.io/oxcalcbank/#/bank/AP3/1/

**Comment by StevenClontz** [comment]
That sounds like something I recall discussing now that you mention it. Any thoughts @siwelwerd ?

**Comment by siwelwerd** [comment]
I am not sure we are talking about the same outcome here?  [AI4](https://teambasedinquirylearning.github.io/calculus/2024/exercises/#/bank/AI4/1/) here is surface areas of a surface of revolution

**Review by TienChih — APPROVED** [review]
Yeah this looks good and makes sense

**Comment by siwelwerd** [comment]
Oh, is this what you were thinking of @TienChih ?  https://github.com/TeamBasedInquiryLearning/calculus/pull/116 

I had kind of a code hygiene question about #112 before approving it, but if that's blocking #116 we could go ahead and merge them both and make a separate issue for later so that #116 makes it into the 2024 Preview edition.

**Pull request merged**
